# Example config file for a new external monitor for hyprland
# monitor=HDMI-A-1,3840x2160@60,1440x0,1.5

# This samsung monitor was 4K so it needed some math to work
# Position: x = -1120, y = -1440
# monitor=HDMI-A-1,3840x2160@60,-1120x-1440,1.5
#
# workspace = 3,monitor:HDMI-A-1,default:true,persistent:true
# workspace = 4,monitor:HDMI-A-1,persistent:true
# workspace = 5,monitor:HDMI-A-1,persistent:true
# workspace = 6,monitor:HDMI-A-1,persistent:true
# workspace = 7,monitor:HDMI-A-1,persistent:true
# workspace = 8,monitor:HDMI-A-1,persistent:true
# workspace = 9,monitor:HDMI-A-1,persistent:true
